#!/bin/sh

echo
echo "Choose a session:"
echo "1) Hyprland"
echo "2) GNOME"
echo "3) dwm"
read -r choice

case "$choice" in
  1)
    exec Hyprland
    ;;
  2)
    # sudo systemctl enable gdm
    systemctl start gdm
    ;;
  3)
    startx
    ;;
  *)
    echo "Invalid choice."
    ;;
esac

